Projects/CSC710_HumanResourceProject_KTBD/Optional/HumanManagement/HumanManagement/Controllers/BeneficiaryController.cs
using HumanManagement.Logics;
using HumanManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HumanManagement.Controllers
{
    [Authorize]
    public class BeneficiaryController : Controller
    {
        private readonly BeneficiaryLogic _logic;
        private readonly EmployeeLogic _employeeLogic;
        private readonly RelationLogic _relationLogic;
        private readonly StateLogic _stateLogic;

        public BeneficiaryController()
        {
            _logic = new BeneficiaryLogic();
            _employeeLogic = new EmployeeLogic();
            _relationLogic = new RelationLogic();
            _stateLogic = new StateLogic();
        }

        public ActionResult Index()
        {
            var employee = _employeeLogic.GetByEmail(User.Identity.Name);
            ViewBag.List = _logic.GetListByEmployeeId(employee.Employee_id);
            return View();
        }

        [HttpGet]
        public ActionResult Insert()
        {
            BindingList();
            return View();
        }

        [HttpPost]
        public ActionResult Insert(BeneficiaryModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = _employeeLogic.GetByEmail(User.Identity.Name);
                model.BeneficiaryEmpId = employee.Employee_id;
                _logic.Create(model);
                return RedirectToAction("index");
            }
            BindingList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            ViewBag.EditMode = 1;
            BeneficiaryModel model = _logic.GetById(id);
            if (_logic.GetById(id) == null)
            {
                return RedirectToAction("index");
            }
            BindingList();
            return View("insert", model);
        }

        [HttpPost]
        public ActionResult Edit(BeneficiaryModel model)
        {
            ViewBag.EditMode = 1;
            if (ModelState.IsValid)
            {
                var employee = _employeeLogic.GetByEmail(User.Identity.Name);
                model.BeneficiaryEmpId = employee.Employee_id;
                _logic.Edit(model);
                return RedirectToAction("index");
            }
            BindingList();
            return View("insert", model);
        }

        public void BindingList()
        {
            ViewBag.StateList = _stateLogic.GetList();
            ViewBag.RelationList = _relationLogic.GetList();
        }

        public ActionResult Delete(int id)
        {
            _logic.Delete(id);
            return RedirectToAction("index");
        }
    }
}

Projects/CSC710_HumanResourceProject_KTBD/Optional/HumanManagement/HumanManagement/Views/Beneficiary/Index.cshtml
@using HumanManagement.Models;
@{
    ViewBag.Title = "Relationship";
}

<div class="container">
    <div class="row">
        <div class="col-12 text-right">
            <a href="~/Beneficiary/Insert" class="btn btn-primary">
                <span class="fa fa-plus-circle"></span>
            </a>
        </div>
    </div>
    <div class="row">
        @foreach (BeneficiaryModel item in ViewBag.List)
        {
            <div class="col-4 border shadow m-3 p-3">
                <table class="w-100">
                    <tr>
                        <td>Name</td>
                        <td>@item.BeneficiaryFName @item.BeneficiaryLName</td>
                    </tr>
                    <tr>
                        <td>Phone</td>
                        <td>@item.BeneficiaryContact</td>
                    </tr>
                    <tr>
                        <td>Relationship</td>
                        <td>@item.RelationShipName</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>@item.BeneficiaryEmail</td>
                    </tr>
                    <tr>
                        <td>Address</td>
                        <td>@item.BeneficiaryAddress</td>
                    </tr>
                    <tr>
                        <td>
                            <a href="~/Beneficiary/Edit?id=@item.BeneficiaryId" class="btn btn-primary">
                                <span class="fa fa-edit"></span>
                            </a>
                        </td>
                        <td class="text-right">
                            <button href="~/Beneficiary/Delete?id=@item.BeneficiaryId" class="btn btn-primary edit">
                                <span class="fa fa-trash"></span>
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        }
    </div>
</div>
@section scripts 
{
    <script>
        $(".edit").click(function () {
            var ok = confirm("Are you delete?");
            if (ok) {
                window.location.href = $(this).attr("href");
            }
        });
    </script>
}

Projects/CSC710_HumanResourceProject_KTBD/Optional/HumanManagement/HumanManagement/Views/Beneficiary/Insert.cshtml
@using HumanManagement.Models;
@using HumanManagement.Utils;
@model BeneficiaryModel
@{
    string action = ViewBag.EditMode == 1 ? "Edit" : "Insert";
    ViewBag.Title = $"{action} Beneficiary";
}

<div class="row">
    <div class="col-md-12">
        <h4>@ViewBag.Title</h4>
        <div class="row">
            @using (Html.BeginForm(action, "Beneficiary", FormMethod.Post, new { @class = "row col-12 padding-0" }))
            {
                if (ViewBag.EditMode == 1)
                {
                    @Html.HiddenFor(q => q.BeneficiaryId)
                }
                <div class="col-md-6 form-group mt-1">
                    @Html.LabelFor(m => m.BeneficiaryFName)
                    @Html.TextBoxFor(m => m.BeneficiaryFName, new { @class = "form-control w-75" })
                    <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryFName, "", new { @class = "text-danger" }) &#160; </div>
                </div>
                <div class="col-md-6 form-group mt-1">
                    @Html.LabelFor(m => m.BeneficiaryLName)
                    @Html.TextBoxFor(m => m.BeneficiaryLName, new { @class = "form-control w-75" })
                    <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryLName, "", new { @class = "text-danger" }) &#160; </div>
                </div>
                <div class="col-12">
                    <div class="row">
                        <div class="col-md-6 form-group mt-1">
                            @Html.LabelFor(m => m.BeneficiaryRelationship)
                            @Html.SelectList(m => m.BeneficiaryRelationship, (object)ViewBag.RelationList, "RelationId", "RelationName", "form-control w-75")
                            <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryRelationship, "", new { @class = "text-danger" }) &#160; </div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="row">
                        <div class="col-md-6 form-group mt-1">
                            @Html.LabelFor(m => m.BeneficiaryContact)
                            @Html.TextBoxFor(m => m.BeneficiaryContact, new { @class = "form-control w-75" })
                            <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryContact, "", new { @class = "text-danger" }) &#160; </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12 form-group mt-2 border-top">
                    <h4 class="mt-2">Address</h4>
                    <div class="row">
                        <div class="col-md-6 form-group mt-1">
                            @Html.LabelFor(m => m.BeneficiaryAddressLine)
                            @Html.TextBoxFor(m => m.BeneficiaryAddressLine, new { @class = "form-control w-75" })
                            <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryAddressLine, "", new { @class = "text-danger" }) &#160; </div>
                        </div>
                        <div class="col-md-6 form-group mt-1">
                            @Html.LabelFor(m => m.BeneficiaryCity)
                            @Html.TextBoxFor(m => m.BeneficiaryCity, new { @class = "form-control w-75" })
                            <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryCity, "", new { @class = "text-danger" }) &#160; </div>
                        </div>
                        <div class="col-md-6 form-group mt-1">
                            @Html.LabelFor(m => m.BeneficiaryState)
                            @Html.SelectList(m => m.BeneficiaryState, (object)ViewBag.StateList, "StateCode", "StateName", "form-control w-75")
                            <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryState, "", new { @class = "text-danger" }) &#160; </div>
                        </div>
                        <div class="col-md-6 form-group mt-1">
                            @Html.LabelFor(m => m.BeneficiaryZipCode)
                            @Html.TextBoxFor(m => m.BeneficiaryZipCode, new { @class = "form-control w-75" })
                            <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryZipCode, "", new { @class = "text-danger" }) &#160; </div>
                        </div>
                        <div class="col-md-6 form-group mt-1">
                            @Html.LabelFor(m => m.BeneficiaryCountry)
                            @Html.TextBoxFor(m => m.BeneficiaryCountry, new { @class = "form-control w-75", disable = "disabled" })
                            <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryCountry, "", new { @class = "text-danger" }) &#160; </div>
                        </div>
                        <div class="col-md-6 form-group mt-1">
                            @Html.LabelFor(m => m.BeneficiaryEmail)
                            @Html.TextBoxFor(m => m.BeneficiaryEmail, new { @class = "form-control w-75" })
                            <div class="small">@Html.ValidationMessageFor(model => model.BeneficiaryEmail, "", new { @class = "text-danger" }) &#160; </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group mt-1">
                            <button type="submit" class="btn btn-primary w-100">Add</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}